# Generated by Django 4.0.4 on 2022-06-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.CharField(max_length=500)),
                ('src2', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
    ]
