# Generated by Django 4.0.4 on 2022-06-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_alter_contact_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
