# Generated by Django 4.0.4 on 2022-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_image_cat1_image_cat2_image_cat3_image_cat4'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='productdetail',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
